name: Run Tests and Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, dom, fileinfo
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # - name: Run Laravel Tests
    #   run: php artisan test
    - name: Run Laravel Tests with Coverage
      run: |
        mkdir -p build/logs
        vendor/bin/phpunit --coverage-clover build/logs/clover.xml

    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: build/logs/clover.xml
        token: ${{ secrets.CODECOV_TOKEN }}

  react-build:

    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install NPM packages
      run: npm install

    - name: Build Frontend
      run: npm run build
